name: zxbase_crypto
# update README when bumping version
version: 1.0.0
homepage: https://github.com/zxbase/zxbase_crypto
description: Crypto helpers.

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cryptography: ^2.0.0

dev_dependencies:
  test: ^1.0.0
  lints: ^2.0.0
