name: zxbase_crypto
version: 3.1.7
homepage: https://github.com/zxbase/zxbase_crypto
description: Crypto helpers.

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  convert: ^3.0.0
  cryptography: ^2.7.0
  pointycastle: ^4.0.0

dev_dependencies:
  test: ^1.0.0
  lints: ^5.0.0
