name: zxbase_crypto
version: 3.1.6
homepage: https://github.com/zxbase/zxbase_crypto
description: Crypto helpers.

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  convert: ^3.0.0
  cryptography: ^2.7.0
  pointycastle: ^3.6.0

dev_dependencies:
  test: ^1.0.0
  lints: ^4.0.0
